apiVersion: v1
kind: LimitRange
metadata:
  name: memory-resource-constraint
spec:
  limits:
    - default:
        memory: 1Gi
      defaultRequest:
        memory: 1Gi
      max:
        memory: 1Gi
      min: 
        memory: 500Mi
      type: Container

# limitare uso di memory dei container di default
# questo viene applicato a livello namespace
