# usati per salvare informazioni sensibili
# comando imperative
# kubectl create secret generic \
# <secret-name> --from-literal=<key>=<value>

apiVersion: v1
kind: Secret
metadata:
  name:  app-secret
data:
  key: value
  key2: value2

# supporta l'encode
# per eseguire l' encode con linux echo -n "valoredaencodare" | base64